on: 
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, edited]    
name: Coveralls
jobs:
  build:
    name: Reporter
    runs-on: Runner_16cores_Deriv-app
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: './.github/actions/setup_node'
      - name: Install dependencies
        uses: "./.github/actions/npm_install_from_cache"
      - name: Build
        uses: "./.github/actions/build"
      - name: Test
        run: JEST_MAX_WORKERS=75% npm run test:jest -- --collectCoverage
      - name: Coveralls
        uses: coverallsapp/github-action@v2
